/* test_golden.c — the golden images (design.md §7.6, §15.2 M4).
 *
 * Fixed screens, rendered by the firmware's row generator and compared
 * with the PPMs in test/host/golden/. The ROM's character set is the one
 * the real ROM writes at boot, read back from character RAM.
 *
 *   test_golden            compare; on a mismatch, write <name>.actual.ppm
 *                          beside the binary for inspection
 *   test_golden --write D  write every image into D instead
 *
 * The images are generated by the code they check, so a golden proves
 * nothing until someone has looked at it (EL §5.7). Look before
 * committing one.
 */

#include <string.h>

#include "guest.h"
#include "render.h"
#include "test_util.h"

#define PPM_HEADER "P6\n256 192\n255\n"
#define PPM_BYTES  (ACE_PIXEL_W * ACE_PIXEL_H * 3u)

static guest_t  g;
static render_t g_r;
static uint8_t  g_rom_charset[ACE_CHARSET_BYTES];
static uint8_t  g_boot_screen[ACE_SCREEN_BYTES];
static uint8_t  g_got[PPM_BYTES];
static uint8_t  g_want[PPM_BYTES];

typedef struct {
    const char *name;
    void (*fill)(uint8_t *screen, uint8_t *charset);
} scene_t;

static void put(uint8_t *screen, int row, int col, const char *s, uint8_t flip) {
    for (; *s; s++) screen[row * 32 + col++] = (uint8_t)(*s ^ flip);
}

/* The real ROM after boot and one line: `2 2 + .` and its answer on the
 * top line, the cursor on the bottom one. */
static void scene_boot(uint8_t *screen, uint8_t *charset) {
    memcpy(screen, g_boot_screen, ACE_SCREEN_BYTES);
    memcpy(charset, g_rom_charset, ACE_CHARSET_BYTES);
}

/* Bit 7 inverts a cell (§7.2): one line normal, the same line inverse,
 * and a full-width inverse space bar between them. */
static void scene_inverse(uint8_t *screen, uint8_t *charset) {
    memset(screen, ' ', ACE_SCREEN_BYTES);
    memcpy(charset, g_rom_charset, ACE_CHARSET_BYTES);
    put(screen, 8, 0, "INVERSE VIDEO: The quick brown", 0);
    for (int c = 0; c < 32; c++) screen[10 * 32 + c] = ' ' | 0x80u;
    put(screen, 12, 0, "INVERSE VIDEO: The quick brown", 0x80u);
}

/* A redefined character changes every cell showing it, normal and
 * inverse, while the screen bytes stay as they were (§7.3). 'A' becomes a
 * box with a diagonal; 'B' is left alone beside it. */
static void scene_redefined(uint8_t *screen, uint8_t *charset) {
    static const uint8_t glyph[8] = { 0xFF, 0xC1, 0xA1, 0x91, 0x89, 0x85, 0x83, 0xFF };
    memset(screen, ' ', ACE_SCREEN_BYTES);
    memcpy(charset, g_rom_charset, ACE_CHARSET_BYTES);
    memcpy(&charset['A' * 8], glyph, 8);
    put(screen, 8, 4, "ABABA BANANA", 0);
    put(screen, 12, 4, "ABABA BANANA", 0x80u);
}

/* Every code with the given character set: $00-$7F on rows 2-8, then
 * $80-$FF, the same glyphs inverse, on rows 12-18, with a blank row
 * between each so the glyphs' top and bottom edges show. */
static void all_codes(uint8_t *screen) {
    memset(screen, ' ', ACE_SCREEN_BYTES);
    for (unsigned code = 0; code < 256u; code++) {
        unsigned row = (code < 128u ? 2u : 12u) + 2u * ((code & 0x7Fu) / 32u);
        screen[row * 32u + code % 32u] = (uint8_t)code;
    }
}

static void scene_glyphs(uint8_t *screen, uint8_t *charset) {
    all_codes(screen);
    memcpy(charset, g_rom_charset, ACE_CHARSET_BYTES);
}

static const scene_t scenes[] = {
    { "boot",      scene_boot },
    { "inverse",   scene_inverse },
    { "redefined", scene_redefined },
    { "glyphs",    scene_glyphs },
};

static void render_rgb(const uint8_t *screen, const uint8_t *charset, uint8_t *rgb) {
    uint16_t row[ACE_PIXEL_W];
    for (unsigned y = 0; y < ACE_PIXEL_H; y++) {
        render_row(&g_r, screen, charset, y, row);
        for (unsigned x = 0; x < ACE_PIXEL_W; x++) {
            /* RGB565 widened by repeating the high bits, so full scale
             * stays full scale. */
            unsigned p = row[x];
            unsigned r5 = p >> 11, g6 = (p >> 5) & 0x3Fu, b5 = p & 0x1Fu;
            *rgb++ = (uint8_t)((r5 << 3) | (r5 >> 2));
            *rgb++ = (uint8_t)((g6 << 2) | (g6 >> 4));
            *rgb++ = (uint8_t)((b5 << 3) | (b5 >> 2));
        }
    }
}

static bool write_ppm(const char *path, const uint8_t *rgb) {
    FILE *f = fopen(path, "wb");
    if (!f) { perror(path); return false; }
    bool ok = fputs(PPM_HEADER, f) >= 0 && fwrite(rgb, 1, PPM_BYTES, f) == PPM_BYTES;
    return fclose(f) == 0 && ok;
}

static bool load_ppm(const char *path, uint8_t *rgb) {
    FILE *f = fopen(path, "rb");
    if (!f) return false;
    char header[sizeof(PPM_HEADER) - 1u];
    bool ok = fread(header, 1, sizeof header, f) == sizeof header &&
              memcmp(header, PPM_HEADER, sizeof header) == 0 &&
              fread(rgb, 1, PPM_BYTES, f) == PPM_BYTES;
    fclose(f);
    return ok;
}

int main(int argc, char **argv) {
    const char *write_dir = (argc == 3 && strcmp(argv[1], "--write") == 0) ? argv[2] : NULL;

    render_init(&g_r, ACE_INK_RGB565, ACE_PAPER_RGB565);

    CHECK(guest_boot(&g, ACE_RAM_19K, 500), "boot");
    guest_type(&g, "2 2 + .\n");
    guest_fields(&g, 10);
    CHECK(strcmp(guest_row(&g.m, 0), "2 2 + . 4  OK") == 0, "top line \"%s\"",
          guest_row(&g.m, 0));
    memcpy(g_boot_screen, ace_screen(&g.m), ACE_SCREEN_BYTES);
    memcpy(g_rom_charset, ace_charset(&g.m), ACE_CHARSET_BYTES);

    for (size_t i = 0; i < sizeof scenes / sizeof scenes[0]; i++) {
        static uint8_t screen[ACE_SCREEN_BYTES], charset[ACE_CHARSET_BYTES];
        scenes[i].fill(screen, charset);
        render_rgb(screen, charset, g_got);

        char path[512];
        if (write_dir) {
            snprintf(path, sizeof path, "%s/%s.ppm", write_dir, scenes[i].name);
            CHECK(write_ppm(path, g_got), "could not write %s", path);
            printf("wrote %s\n", path);
            continue;
        }

        snprintf(path, sizeof path, "%s/%s.ppm", PICO_ACE_GOLDEN_DIR, scenes[i].name);
        if (!load_ppm(path, g_want)) {
            CHECK(false, "%s: missing or malformed; write it with --write, and look at "
                  "it before committing", path);
            continue;
        }
        if (memcmp(g_got, g_want, PPM_BYTES) != 0) {
            size_t first = 0, diff = 0;
            for (size_t p = 0; p < PPM_BYTES; p += 3u) {
                if (memcmp(&g_got[p], &g_want[p], 3u) != 0) {
                    if (!diff) first = p / 3u;
                    diff++;
                }
            }
            CHECK(false, "%s: %zu pixel(s) differ, first at (%zu,%zu)", scenes[i].name, diff,
                  first % ACE_PIXEL_W, first / ACE_PIXEL_W);
            snprintf(path, sizeof path, "%s.actual.ppm", scenes[i].name);
            if (write_ppm(path, g_got)) fprintf(stderr, "    rendered image written to %s\n", path);
        }
    }

    TEST_DONE();
}
