#!/usr/bin/env python3
"""Write src/core/font.c from third_party/font8x8/font8x8_basic.h.

The emulator's own pages use a public-domain 8x8 font, never the guest's
character RAM (design.md §7.5). The upstream file is kept verbatim; this
tool only changes its layout. font8x8 puts a row's first pixel in bit 0;
the Ace's row generator wants it in bit 7 (design.md §7.2), so every byte
is reversed. Nothing else changes: 128 glyphs, 8 rows, in code order.

test_render checks the result against the upstream README's 'A' and
renders the whole set to a golden image, which someone must look at
(design.md §7.6).

    tools/mkfont.py                 # rewrite src/core/font.c
    tools/mkfont.py --check         # exit 1 if src/core/font.c is stale
"""

import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "third_party/font8x8/font8x8_basic.h"
OUT = ROOT / "src/core/font.c"


def glyphs(text):
    body = text[text.index("{", text.index("font8x8_basic")) + 1:]
    rows = re.findall(r"\{([^}]*)\}", body)
    out = []
    for row in rows[:128]:
        out.append([int(v, 16) for v in re.findall(r"0x[0-9A-Fa-f]{2}", row)])
    if len(out) != 128 or any(len(g) != 8 for g in out):
        sys.exit(f"{SRC}: expected 128 glyphs of 8 bytes")
    return out


def reverse(b):
    return int(f"{b:08b}"[::-1], 2)


def emit(gs):
    lines = [
        "/* font.c — the emulator's own font (design.md §7.5). Generated by",
        " * tools/mkfont.py from third_party/font8x8/font8x8_basic.h (Daniel",
        " * Hepper, after Marcel Sondaar and IBM's VGA fonts; public domain),",
        " * with each byte reversed so that bit 7 is the leftmost pixel. Do not",
        " * edit; rerun the tool. */",
        "",
        '#include "font.h"',
        "",
        "const uint8_t ace_font[ACE_CHARSET_BYTES] = {",
    ]
    for code, g in enumerate(gs):
        name = chr(code) if 0x20 < code < 0x7F else f"U+{code:04X}"
        if code == 0x20:
            name = "space"
        vals = ", ".join(f"0x{reverse(b):02X}" for b in g)
        lines.append(f"    {vals},   /* {name} */")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    text = emit(glyphs(SRC.read_text()))
    if args.check:
        if OUT.read_text() != text:
            sys.exit(f"{OUT} is stale; run tools/mkfont.py")
        return
    OUT.write_text(text)


if __name__ == "__main__":
    main()
