# embed_rom.cmake — turns roms/ace.rom into ace_rom.c, a const array the
# core links, and refuses any file whose SHA-1 is not the Ace ROM's
# (design.md §10.2). Run at build time, so a damaged or substituted file
# fails the build instead of booting and then misbehaving (EL §8.1).
#
#   cmake -DROM=<ace.rom> -DSHA1=<expected> -DOUT=<ace_rom.c> -P embed_rom.cmake

if (NOT EXISTS "${ROM}")
    message(FATAL_ERROR "embed_rom: ${ROM} does not exist")
endif()

file(SHA1 "${ROM}" actual)
if (NOT actual STREQUAL SHA1)
    message(FATAL_ERROR
        "embed_rom: ${ROM} has SHA-1 ${actual}, not the Ace ROM's ${SHA1} "
        "(design.md §10.2). Restore it from git; do not replace it.")
endif()

file(READ "${ROM}" hex HEX)
string(LENGTH "${hex}" digits)
math(EXPR bytes "${digits} / 2")
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," body "${hex}")
# Sixteen bytes a line.
string(REGEX REPLACE "((0x..,){16})" "\\1\n    " body "${body}")

file(WRITE "${OUT}.tmp"
"/* Generated by cmake/embed_rom.cmake from roms/ace.rom, SHA-1 ${SHA1}.
 * The ROM is not under this project's GPL: see roms/COPYING.md. */
#include \"ace_rom.h\"

const uint8_t ace_rom[${bytes}] = {
    ${body}
};
")
file(RENAME "${OUT}.tmp" "${OUT}")
